export const GET_FEATURED_MOVIES = {
  LOADING: 'GET_FEATURED_MOVIES_LOADING',
  SUCCESS: 'GET_FEATURED_MOVIES_SUCCESS',
  ERROR: 'GET_FEATURED_MOVIES_ERROR'
}

export const GET_MOVIE = {
  LOADING: 'GET_MOVIE_LOADING',
  SUCCESS: 'GET_MOVIE_SUCCESS',
  ERROR: 'GET_MOVIE_ERROR'
}

export const SEARCH_MOVIES = {
  LOADING: 'SEARCH_MOVIES_LOADING',
  SUCCESS: 'SEARCH_MOVIES_SUCCESS',
  ERROR: 'SEARCH_MOVIES_ERROR'
}

export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS'