export const ADD_TO_QUEUE = {
  LOADING: 'ADD_TO_QUEUE_LOADING',
  SUCCESS: 'ADD_TO_QUEUE_SUCCESS',
  ERROR: 'ADD_TO_QUEUE_ERROR'
}

export const REMOVE_FROM_QUEUE = {
  LOADING: 'REMOVE_FROM_QUEUE_LOADING',
  SUCCESS: 'REMOVE_FROM_QUEUE_SUCCESS',
  ERROR: 'REMOVE_FROM_QUEUE_ERROR'
}